#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=59568678970
BundleId=com.sps.pxelfall
ClientId=59568678970-5pv3ri1hmp5grl1urilf4noqodfu7j42.apps.googleusercontent.com

*/

#define kAppID "59568678970"
#define kBundleID "com.sps.pxelfall"
#define kClientID "59568678970-5pv3ri1hmp5grl1urilf4noqodfu7j42.apps.googleusercontent.com"

#endif


